spring.application.name=group7

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/iste240?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456789

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# SQL Seed Data
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql